/**
 * PWA Install & Asset Generator Utility (Phase 7.3 - Path A)
 */

let deferredPrompt: any = null;
let isPromptReady = false;

if (typeof window !== 'undefined') {
  window.addEventListener('beforeinstallprompt', (e) => {
    e.preventDefault();
    deferredPrompt = e;
    isPromptReady = true;
    window.dispatchEvent(new CustomEvent('pwa_prompt_ready'));
  });

  window.addEventListener('appinstalled', () => {
    deferredPrompt = null;
    isPromptReady = false;
    window.dispatchEvent(new CustomEvent('pwa_installed'));
  });
}

export function isPWAInstallAvailable(): boolean {
  return isPromptReady;
}

export async function promptPWAInstall(): Promise<{ outcome: 'accepted' | 'dismissed' | 'unsupported' }> {
  if (!deferredPrompt) {
    return { outcome: 'unsupported' };
  }

  try {
    deferredPrompt.prompt();
    const choiceResult = await deferredPrompt.userChoice;
    deferredPrompt = null;
    isPromptReady = false;
    return { outcome: choiceResult.outcome };
  } catch (err) {
    console.error('PWA install error:', err);
    return { outcome: 'unsupported' };
  }
}

export function generatePWAManifest(appName: string, themeColor: string = '#00f0ff'): string {
  const cleanName = appName || 'ALTREX Web App';
  const cleanShort = cleanName.length > 12 ? cleanName.substring(0, 12) : cleanName;

  const manifest = {
    name: cleanName,
    short_name: cleanShort,
    description: `${cleanName} — Built with ALTREX CODE Cyber IDE`,
    start_url: '/',
    display: 'standalone',
    background_color: '#05070f',
    theme_color: themeColor,
    orientation: 'portrait-primary',
    icons: [
      {
        src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192" width="192" height="192"><rect width="192" height="192" fill="%2305070f"/><polygon points="96,24 168,144 24,144" fill="none" stroke="%2300f0ff" stroke-width="12"/><text x="96" y="125" fill="%2300f0ff" font-family="monospace" font-size="44" font-weight="bold" text-anchor="middle">ATX</text></svg>',
        sizes: '192x192',
        type: 'image/svg+xml',
        purpose: 'any maskable',
      },
      {
        src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512"><rect width="512" height="512" fill="%2305070f"/><polygon points="256,64 448,384 64,384" fill="none" stroke="%2300f0ff" stroke-width="32"/><text x="256" y="330" fill="%2300f0ff" font-family="monospace" font-size="120" font-weight="bold" text-anchor="middle">ATX</text></svg>',
        sizes: '512x512',
        type: 'image/svg+xml',
        purpose: 'any maskable',
      },
    ],
  };

  return JSON.stringify(manifest, null, 2);
}

export function generateServiceWorker(appName: string): string {
  return `// Cache-first Service Worker for ${appName} generated by ALTREX CODE
const CACHE_NAME = 'altrex-cache-v1';
const PRECACHE_ASSETS = [
  '/',
  '/index.html',
  '/manifest.json'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(PRECACHE_ASSETS).catch((e) => console.warn('PWA precache notice:', e));
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cache) => {
          if (cache !== CACHE_NAME) {
            return caches.delete(cache);
          }
        })
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        if (!response || response.status !== 200 || response.type !== 'basic') {
          return response;
        }
        const responseToCache = response.clone();
        caches.open(CACHE_NAME).then((cache) => {
          cache.put(event.request, responseToCache);
        });
        return response;
      }).catch(() => caches.match('/index.html'));
    })
  );
});
`;
}
