import React, { useState } from 'react';
import { Terminal, CheckCircle2, XCircle, Copy, Check, Clock, Play } from 'lucide-react';

interface OutputPreviewProps {
  output: string;
  error?: string;
  exitCode?: number;
  durationMs?: number;
  language: string;
  onRerun?: () => void;
}

export function OutputPreview({
  output,
  error,
  exitCode = 0,
  durationMs,
  language,
  onRerun,
}: OutputPreviewProps) {
  const [copied, setCopied] = useState(false);
  const isSuccess = exitCode === 0 && !error;

  const handleCopy = () => {
    const text = (output ? output + '\n' : '') + (error || '');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col h-full bg-[#03060f] text-slate-200 font-mono select-text">
      {/* Header Bar */}
      <div className="h-10 bg-[#080d19] border-b border-slate-800 flex items-center px-4 justify-between shrink-0 text-xs">
        <div className="flex items-center gap-2">
          <Terminal className="w-4 h-4 text-cyan-400" />
          <span className="font-bold text-slate-200">Execution Console</span>
          <span className="text-[10px] px-2 py-0.5 rounded bg-cyan-950/80 text-cyan-300 border border-cyan-500/30">
            {language}
          </span>
          {durationMs !== undefined && (
            <span className="text-[11px] text-slate-500 flex items-center gap-1">
              <Clock className="w-3 h-3" /> {durationMs}ms
            </span>
          )}
        </div>

        <div className="flex items-center gap-2">
          {isSuccess ? (
            <span className="flex items-center gap-1 text-[11px] text-emerald-400 font-bold">
              <CheckCircle2 className="w-3.5 h-3.5" /> Success (Exit {exitCode})
            </span>
          ) : (
            <span className="flex items-center gap-1 text-[11px] text-red-400 font-bold">
              <XCircle className="w-3.5 h-3.5" /> Failed (Exit {exitCode})
            </span>
          )}

          {onRerun && (
            <button
              onClick={onRerun}
              className="p-1.5 rounded hover:bg-slate-800 text-cyan-400 hover:text-cyan-300 transition-colors"
              title="Rerun execution"
            >
              <Play className="w-3.5 h-3.5" />
            </button>
          )}

          <button
            onClick={handleCopy}
            className="p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
            title="Copy output"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
          </button>
        </div>
      </div>

      {/* Terminal Output Area */}
      <div className="flex-1 overflow-auto p-4 space-y-3 text-xs leading-relaxed">
        {output && (
          <pre className="text-emerald-300 whitespace-pre-wrap font-mono selection:bg-emerald-900 selection:text-white">
            {output}
          </pre>
        )}
        {error && (
          <div className="mt-2 pt-2 border-t border-red-500/20">
            <div className="text-[11px] font-bold text-red-400 uppercase tracking-wider mb-1">
              STDERR / Compilation Notice:
            </div>
            <pre className="text-red-300 whitespace-pre-wrap font-mono selection:bg-red-900 selection:text-white">
              {error}
            </pre>
          </div>
        )}
        {!output && !error && (
          <div className="text-slate-500 italic">No output generated by process.</div>
        )}
      </div>
    </div>
  );
}
